### ISSUE TITLE
https error loading the site

### ISSUE THREAD

**Issue by unrealbe** [Sunxperous/plugmixer#4]
Cant open the plugin anymore since you're https certificat reports errors

**Comment by Sunxperous** [comment]
Are you able to provide more information? Is this the bookmark script or the Chrome extension? What is the exact error message shown? Thanks!

**Comment by unrealbe** [comment]
The bookmark script, I cannot open:
https://plugmixer.sunwj.com/local

Secure connection failed,

I will try the addon

**Comment by Sunxperous** [comment]
Which browser and version are you using? Alternatively, you can use https://plugmixer-serve.sunwj.com/plugmixer_local.js for now.
